# Pima Indians Diabetes Database
https://www.kaggle.com/uciml/pima-indians-diabetes-database

Cet ensemble de données est à l'origine de l'Institut national du diabète et des maladies digestives et rénales. 
Il est fourni avec l'aimable autorisation de la base de données sur le diabète des Indiens Pima et est disponible sur Kaggle: 
Il se compose de plusieurs variables prédictives médicales et d'une variable cible, le résultat. 
Les variables prédictives comprennent le nombre de grossesses que la patiente a eues, son IMC, son taux d'insuline, son âge, etc. 

L'ensemble de données comporte 9 colonnes, comme indiqué ci-dessous;

  Pregnancies              - Nombre de fois enceinte
  Glucose                  - Concentration de glucose plasmatique à 2 heures dans un test oral de tolérance au glucose
  BloodPressure            - Tension artérielle diastolique (mm Hg)
  SkinThickness            - Épaisseur du pli cutané du triceps (mm)
  Insulin                  - Insuline sérique 2 heures (mu U / ml)
  BMI                      - Indice de masse corporelle (poids en kg / (taille en m) ^ 2)
  DiabetesPedigreeFunction - Fonction généalogique du diabète
  Age                            - Années d'âge)
  Outcome                  - Variable de classe (0 ou 1) 268 sur 768 sont 1, les autres sont 0



Énoncé du problème

Il s'agit d'un problème de classification de l'apprentissage automatique supervisé. 
L'objectif est de prédire si un patient est diabétique ou non, sur la base de certaines mesures diagnostiques incluses dans l'ensemble de données.

0 - Absence de diabète

1 - Présence de diabète



Dans ce projet, nous utilisonsons python3 et le notebook Jupyter.  
Nous allons parcourir le projet en important l'ensemble de données, en effectuant une analyse exploratoire des données pour obtenir des informations et comprendre à quoi ressemble l'ensemble de données, puis construire le modèle. 
Nous utilisonsons en outre .

Les 7 étapes de l'apprentissage automatique , fournit le cadre général suivant des étapes de l'apprentissage automatique supervisé;

    Collecte de données
    Préparation des données
    Choisir un modèle
    Entraîner le modèle
    Évaluer le modèle
    Réglage des paramètres
    Faire des prédictions

Commençons donc par importer les bibliothèques requises. 
Nous importons des bibliothèques d'analyse de données ( pandas, numpy) et des bibliothèques de visualisation ( matplotlib, seaborn). 
En plus de cela, nous importons également warningsafin que les avertissements soient masqués du notebook au cas où il y en aurait. 
Pour résoudre le problème, nous devrons analyser les données, effectuer toute transformation et normalisation requises, appliquer un algorithme d'apprentissage automatique, entraîner un modèle, vérifier les performances du modèle entraîné et itérer avec d'autres algorithmes jusqu'à ce que nous trouvions le plus performant pour notre type. de l'ensemble de données.

___

In [1]:
# importer les librairies 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# importer les librairies machine learning

In [5]:
# importer la base de données
df = pd.read_csv('diabetes.csv')
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0